import { Router } from 'express';
import healthRoutes from '../modules/health/health.routes';
import authRoutes from '../modules/auth/auth.routes';
import contentRoutes from '../modules/content/content.routes';
import blogRoutes from '../modules/blog/blog.routes';
import feedbackRoutes from '../modules/feedback/feedback.routes';
import queriesRoutes from '../modules/queries/queries.routes';
import contentTypeRoutes from '../modules/content-type/content-type.routes';
import { categoryRoutes } from '../modules/category';
import { collectionRoutes } from '../modules/collection';
import { styleRoutes } from '../modules/style';
import { bodyPlacementRoutes } from '../modules/body-placement';
const router = Router();
router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/content', contentRoutes);
router.use('/blog', blogRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/queries', queriesRoutes);
router.use('/content-types', contentTypeRoutes);
router.use('/categories', categoryRoutes);
router.use('/collections', collectionRoutes);
router.use('/styles', styleRoutes);
router.use('/body-placements', bodyPlacementRoutes);

export default router;
